<?php
$rules = array
(
0=>array(id=>0,rule=>"[No Number rule] Exploitation begins at home."), 
 1=>array(id=>1,rule=>"Once you have their money ... never give it back."),
 2=>array(id=>3,rule=>"Never pay more for an acquisition than you have to."),
 3=>array(id=>6,rule=>"Never allow family to stand in the way of opportunity."),
 4=>array(id=>6,rule=>"A man is only worth the sum of his possessions. (From Enterprise, episode 'Acquisition'; sloppy script-writing, as rule 6 (see above) was already given in DS9)"),
 5=>array(id=>7,rule=>"Keep your ears open."),
 6=>array(id=>8,rule=>"Small print leads to large risk."),
 7=>array(id=>9,rule=>"Opportunity plus instinct equals profit."),
 8=>array(id=>10,rule=>"Greed is eternal."),
 9=>array(id=>13,rule=>"Anything worth doing is worth doing for money."),
10=>array(id=>16,rule=>"A deal is a deal ... until a better one comes along."),
11=>array(id=>17,rule=>"A contract is a contract is a contract (but only between Ferengi)."),
12=>array(id=>18,rule=>"A Ferengi without profit is no Ferengi at all."),
13=>array(id=>19,rule=>"Satisfaction is not guaranteed."),
14=>array(id=>21,rule=>"Never place friendship above profit."),
15=>array(id=>22,rule=>"A wise man can hear profit in the wind."),
16=>array(id=>23,rule=>"Nothing is more important than your health--except for your money."),
17=>array(id=>27,rule=>"There's nothing more dangerous than an honest businessman."),
18=>array(id=>31,rule=>"Never make fun of a Ferengi's mother ... insult something he cares about instead."),
19=>array(id=>33,rule=>"It never hurts to suck up to the boss."),
20=>array(id=>34,rule=>"War is good for business."),
21=>array(id=>35,rule=>"Peace is good for business."),
22=>array(id=>40,rule=>"She can touch your lobes but never your latinum."),
23=>array(id=>41,rule=>"Profit is its own reward."),
24=>array(id=>44,rule=>"Never confuse wisdom with luck."),
25=>array(id=>45,rule=>"Expand, or die."),
26=>array(id=>47,rule=>"Don't trust a man wearing a better suit than your own."),
27=>array(id=>48,rule=>"The bigger the smile, the sharper the knife."),
28=>array(id=>49,rule=>"Females and finance don't mix."),
29=>array(id=>52,rule=>"Never ask when you can take."),
30=>array(id=>57,rule=>"Good customers are as rare as latinum -- treasure them."),
31=>array(id=>58,rule=>"There is no substitute for success."),
32=>array(id=>59,rule=>"Free advice is seldom cheap."),
33=>array(id=>60,rule=>"Keep your lies consistent."),
34=>array(id=>62,rule=>"The riskier the road, the greater the profit."),
35=>array(id=>65,rule=>"Win or lose, there's always Hyperian beetle snuff."),
36=>array(id=>75,rule=>"Home is where the heart is ... but the stars are made of latinum."),
37=>array(id=>76,rule=>"Every once in a while, declare peace. It confuses the hell out of your enemies."),
38=>array(id=>79,rule=>"Beware of the Vulcan greed for knowledge."),
39=>array(id=>82,rule=>"The flimsier the product, the higher the price."),
40=>array(id=>85,rule=>"Never let the competition know what you're thinking."),
41=>array(id=>89,rule=>"Ask not what your profits can do for you, but what you can do for your profits."),
42=>array(id=>94,rule=>"Females and finances don't mix."),
43=>array(id=>97,rule=>"Enough ... is never enough."),
44=>array(id=>98,rule=>"Every man has his price. (DS9 season 6, episode 19 - 'In the Pale Moonlight')"),
45=>array(id=>99,rule=>"Trust is the biggest liability of all."),
46=>array(id=>102,rule=>"Nature decays, but latinum lasts forever."),
47=>array(id=>103,rule=>"Sleep can interfere with profit. (DS9 season 2, episode 7 - 'Rules of Acquisition')"),
48=>array(id=>104,rule=>"Faith moves mountains ... of inventory."),
49=>array(id=>106,rule=>"There is no honour in poverty."),
50=>array(id=>109,rule=>"Dignity and an empty sack is worth the sack."),
51=>array(id=>111,rule=>"Treat people in your debt like family ... exploit them."),
52=>array(id=>112,rule=>"Never have sex with the boss's sister."),
53=>array(id=>113,rule=>"Always have sex with the boss."),
54=>array(id=>117,rule=>"You can't free a fish from water."),
55=>array(id=>121,rule=>"Everything is for sale, even friendship."),
56=>array(id=>123,rule=>"Even a blind man can recognize the glow of latinum."),
57=>array(id=>125,rule=>"You can't make a deal if you're dead. (DS9 season 7, episode 8 - The Siege of AR-558')"),
58=>array(id=>139,rule=>"Wives serve, brothers inherit."),
59=>array(id=>141,rule=>"Only fools pay retail."),
60=>array(id=>144,rule=>"There's nothing wrong with charity ... as long as it winds up in your pocket."),
61=>array(id=>162,rule=>"Even in the worst of times someone turns a profit."),
62=>array(id=>168,rule=>"Whisper your way to success. (DS9 season 7, episode 9 - 'Covenant')"),
63=>array(id=>177,rule=>"Know your enemies ... but do business with them always."),
64=>array(id=>181,rule=>"Not even dishonesty can tarnish the shine of profit."),
65=>array(id=>189,rule=>"Let others keep their reputation. You keep their money."),
66=>array(id=>190,rule=>"Hear all, trust nothing."),
67=>array(id=>192,rule=>"Never cheat a Klingon ... unless you're sure you can get away with it."),
68=>array(id=>194,rule=>"It's always good business to know about new customers before they walk in the door."),
69=>array(id=>202,rule=>"The justification for profit is profit."),
70=>array(id=>203,rule=>"New customers are like razortoothed grubworms. They can be succulent, but sometimes they can bite back."),
71=>array(id=>208,rule=>"Sometimes the only thing more dangerous than a question is an answer."),
72=>array(id=>211,rule=>"Employees are rungs on the ladder of success. Don't hesitate to step on them."),
73=>array(id=>214,rule=>"Never begin a negotiation on an empty stomach."),
74=>array(id=>217,rule=>"You can't free a fish from water."),
75=>array(id=>218,rule=>"Always know what you're buying."),
76=>array(id=>223,rule=>"Beware the man who doesn't make time for oo-mox."),
77=>array(id=>229,rule=>"Latinum lasts longer than lust."),
78=>array(id=>236,rule=>"You can't buy fate."),
79=>array(id=>239,rule=>"Never be afraid to mislabel a product."),
80=>array(id=>242,rule=>"More is good ... all is better."),
81=>array(id=>255,rule=>"A wife is a luxury ... a smart accountant is a necessity."),
82=>array(id=>261,rule=>"A wealthy man can afford anything except a conscience."),
83=>array(id=>263,rule=>"Never allow doubt to tarnish your love of latinum."),
84=>array(id=>266,rule=>"When in doubt, lie."),
85=>array(id=>284,rule=>"Deep down everyone's a Ferengi."),
86=>array(id=>285,rule=>"No good deed ever goes unpunished."),
87=>array(id=>286,rule=>"[Quark's rule] When Morn leaves, it's all over.") 
);
print_r($rules);